services:
  - type: web
    name: torque-wizard-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 