services:
  - type: web
    name: torque-wizard-api
    env: node
    buildCommand: |
      cd server
      npm install
    startCommand: cd server && NODE_ENV=production node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true
    plan: free

  - type: web
    name: torque-wizard-frontend
    env: static
    buildCommand: |
      cd torque-wizard-app
      npm install --legacy-peer-deps
      CI=false npm run build
    staticPublishPath: torque-wizard-app/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://torque-wizard-api.onrender.com
      - key: CI
        value: false
      - key: NODE_OPTIONS
        value: --max_old_space_size=4096
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    autoDeploy: true
    plan: free 